#!/usr/bin/env node

var commander = require('commander');
var models = require('../lib/models');
var sequelize {
  fixtures: require('sequelize-fixtures')
}

sequelize.fixtures.loadFile('*.yml', models, function(fixtures){
    console.log('fixtures have been loaded into the database')
})