#!/usr/bin/env node

_ = require('underscore');
models = require('../lib/models');

validators = _.object(_.map(models, function(model){
    attributes = model.rawAttributes;
    modelKeys = _.keys(attributes);
    modelValidators = _.pluck(attributes, 'validate');
    return [model.name, _.object(modelKeys, modelValidators)];
}));

console.log(validators);