#!/usr/bin/env node

var models = require('../lib/models');
var sequelize = models.sequelize;
sequelize.fixtures = require('sequelize-fixtures');

sequelize.sync({force: true}).success(function(){
    console.log('Created a fresh newslynx database.');
    sequelize.fixtures.loadFile('../test/fixtures/*.yml', models, function(fixtures){
        console.log('Finished loading fixtures.');
        console.log(fixtures);
    });
});
